# Generated by Django 4.0.6 on 2022-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portadas')),
                ('name', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
    ]
