# Generated by Django 4.0.6 on 2022-08-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_name_biblioteca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='portadas'),
        ),
    ]
